version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn test
      - run: mvn clean install

  deploy:
    docker:
      - image: circleci/buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name:
            Deploy app on Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - Local
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build